# 多环境共同的部分&指定激活那个环境
spring:
  profiles:
    active: dev  # 指定当前激活的时开发环境
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: root123456
  data:
    redis:
      port: 6379
      host: localhost

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true  #开启驼峰命名和下划线命名的自动转换

mybatis-plus:
#  config-location: classpath:mybatis-config.xml #mybatis 的配置文件路径,目前也用不到
#  mapper-locations: classpath:mapper/*Mapper.xml   #省略mapper文件的@Mapper注释
  type-aliases-package: pojo   #批量注册指定包下的类，在mapper.xml 中就不需要类的全类名
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除的配置
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0

#  #以下是数据库策略，目前用不到
#  global-config:
#    #数据库配置
#    db-config:
#       id-type: auto       #id自增长
#      table-prefix: tb_    #表名前缀为tb_，表名为前缀拼接类名


---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080

---
#测试环境
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8081





